import Home from "./home/page";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Teste Next.js Home | Tailwind CSS",
  description: "Generated by create next app",
};

export default function Page() {
  return <Home />;
}
