import { Table, TableHead, TableHeader, TableRow } from "@/components/ui/table";

import { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { PlusCircle } from "lucide-react";

import { TableBodyList } from "@/components/table-body-list";
import { ProductCreationDialog } from "@/components/product-creation-dialog";
import { ProductFilters } from "@/components/ProductFilters";

export const metadata: Metadata = {
  title: "Teste Next.js Produtos | Tailwind CSS",
  description: "Generated by create next app",
};

export default async function Product() {
  return (
    <main className="flex flex-col gap-4">
      <div className="flex justify-between gap-4 max-md:flex-col align-middle pt-7">
        <h1 className="text-3xl font-bold tracking-tight">Produtos</h1>
        <ProductCreationDialog>
          <Button variant="outline" size="default">
            <PlusCircle className="mr-2 h-3 w-3" />
            Adicionar produto
          </Button>
        </ProductCreationDialog>
      </div>
      <ProductFilters />
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="min-w-[90px]">Imagem</TableHead>
              <TableHead className="min-w-[120px] w-[150px]">Nome</TableHead>
              <TableHead className="min-w-[120px]">Categoria</TableHead>
              <TableHead className="min-w-[120px]">Preço</TableHead>
              <TableHead className="min-w-[120px]">Descrição</TableHead>
            </TableRow>
          </TableHeader>
          <TableBodyList />
        </Table>
      </div>
    </main>
  );
}
