import { Metadata } from "next";

import Dashboard from "@/components/dashboard";

export const metadata: Metadata = {
  title: "Home | Tailwind CSS",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <main className="flex flex-col gap-4">
      <Dashboard />
    </main>
  );
}
